import type { Language } from "../shared/types";

export const LANGUAGES: Array<{ code: Language; label: string }> = [
  { code: "es", label: "Español" },
  { code: "en", label: "English" },
  { code: "fr", label: "Français" },
  { code: "pt", label: "Português" },
  { code: "it", label: "Italiano" },
  { code: "de", label: "Deutsch" },
];

const es = {
  navLaunch: "Lanzar", navProjects: "Proyectos", navCleanup: "Limpieza", navAccounts: "Cuentas", navInventory: "Inventario", navUpdates: "Actualizaciones", navHelp: "Guía y ajustes",
  ready: "Listo", notInstalled: "No instalado", plugins: "plugins", skills: "skills", connectedAccount: "Cuenta conectada", connectMissing: "Falta conectar",
  start: "Iniciar", resume: "Continuar sesión", install: "Instalar",
  launchEyebrow: "Bahía de lanzamiento", launchTitle1: "Elige el proyecto.", launchTitle2: "Enciende el agente.", launchIntro: "Tres herramientas, una sola puerta de entrada y ninguna credencial compartida.",
  activeProject: "Proyecto activo", chooseFolder: "Elegir una carpeta", changeFolder: "Cambiar carpeta", availableAgents: "Agentes disponibles",
  privateTitle: "Sesiones privadas por diseño", privateText: "El launcher no incluye ni copia tus claves. Cada usuario inicia sesión directamente con el proveedor elegido.",
  accountsEyebrow: "Identidad local", accountsTitle: "Tus cuentas viven fuera del launcher.", accountsIntro: "Cada proveedor conserva su acceso en el perfil actual del sistema. Al compartir el instalador, los demás comienzan desde cero.",
  connected: "Conectada", disconnected: "Sin conectar", changeAccount: "Cambiar cuenta", signIn: "Iniciar sesión", signOut: "Cerrar sesión", manageAccount: "Gestionar cuenta",
  sharedComputer: "Para equipos compartidos", sharedComputerText: "Usa una cuenta del sistema distinta por persona. Así también quedan separados los historiales, configuraciones y credenciales guardados por cada CLI.",
  inventoryEyebrow: "Mesa de diagnóstico", inventoryTitle: "Todo lo que cada agente carga.", installedCount: "{count} instalados", availableCount: "{count} disponibles", active: "Activo", user: "usuario",
  noPlugins: "No se detectaron plugins instalados.", noSkills: "No se detectaron skills.", mcpDetected: "Servidores MCP detectados", technicalOutput: "Ver salida técnica", noMcp: "Sin servidores MCP detectados o herramienta no instalada.", openDocs: "Abrir documentación de {tool}",
  maintenance: "Mantenimiento", updatesTitle: "Versiones claras, cambios bajo control.", updatesIntro: "La comprobación es automática. Las actualizaciones abren la terminal para que puedas ver exactamente qué cambia.", checking: "Comprobando…", checkNow: "Comprobar ahora", noHiddenInstallers: "No se ejecutan instaladores ocultos.",
  notChecked: "Sin comprobar", detectedInstall: "Instalación detectada", notYetInstalled: "Aún no está instalado", current: "Actual", available: "Disponible", upToDate: "Al día", update: "Actualizar", launcherChannel: "Canal de actualización del instalador", searchUpdate: "Buscar actualización",
  guideEyebrow: "Guía y ajustes", guideTitle: "Menos proyectos abiertos. Más proyectos publicados.", howToStart: "Cómo empezar", stepProject: "Elige un proyecto", stepProjectText: "Selecciona la carpeta que contiene tu código.", stepAccount: "Conecta tu cuenta", stepAccountText: "El proveedor abre su propio acceso seguro.", stepAgent: "Inicia el agente", stepAgentText: "La terminal se abre en la carpeta correcta.",
  preferences: "Preferencias", checkTools: "Comprobar herramientas", checkToolsText: "Busca nuevas versiones al iniciar", updateLauncher: "Actualizar el launcher", updateLauncherText: "Comprueba el canal de versiones", startSystem: "Iniciar con el sistema", startSystemText: "Abre el panel al entrar en tu cuenta",
  missingTool: "¿Falta alguna herramienta?", officialRequirements: "Consulta su instalación y requisitos oficiales.", localPanel: "Panel local", readingSystem: "Leyendo el sistema…", shellReady: "{shell} listo", refreshStatus: "Actualizar estado", language: "Idioma", settingsSaved: "Preferencias guardadas.", diagnosticError: "No se pudo completar el diagnóstico.",
  projectsEyebrow: "Biblioteca local", projectsTitle: "Encuentra uno. Termínalo.", projectsIntro: "Busca incluso si no recuerdas el nombre exacto, recupera el contexto y deja visible el próximo paso hasta publicarlo.", addProjectFolder: "Añadir carpeta", scanProjects: "Buscar proyectos", scanningProjects: "Buscando…", useProject: "Usar proyecto", openFolder: "Abrir carpeta", projectSelected: "Proyecto seleccionado: {name}", projectFolderOpened: "Carpeta abierta.", noProjectsTitle: "Todavía no encontramos proyectos.", noProjectsText: "Añade tu carpeta de trabajo. También encontraremos apps y plugins locales aunque no estén en GitHub.", noProjectDescription: "Sin descripción todavía. Añade un README para recordar qué hace.", localFolder: "Carpeta local", detectedProjects: "{count} proyectos detectados", searchLocations: "Carpetas de búsqueda", automaticLocations: "Ubicaciones habituales incluidas", removeRoot: "Quitar", folderOpenError: "No se pudo abrir la carpeta.",
  projectSearchPlaceholder: "Busca por nombre, descripción, tecnología o ruta…", searchProjectsLabel: "Buscar proyectos", clearSearch: "Limpiar búsqueda", projectFilters: "Filtros de proyecto", filterAll: "Todos", filterFocus: "En foco", filterRisk: "En riesgo", filterUnplanned: "Sin plan", filterClosed: "Cerrados", resultsCount: "{count} coincidencias", noSearchTitle: "Ningún proyecto coincide.", noSearchText: "Prueba con parte del nombre, una tecnología o una palabra de su descripción.",
  focusDesk: "Mesa de cierre", focusDeskEmpty: "Elige qué merece terminarse.", focusDeskEmptyText: "Pon hasta tres proyectos en foco. El launcher te mostrará siempre el siguiente movimiento.", planFirstProject: "Planificar el primero", finishNow: "Empuja esto ahora", continueProject: "Continuar", missingNextAction: "Falta definir un próximo paso pequeño y concreto.", blockedBy: "Bloqueo",
  finishPlan: "Plan de cierre", finishPlanIntro: "No planifiques todo el proyecto. Define la línea de meta y el siguiente paso que puedas completar en una sesión.", phase: "Fase", deadline: "Fecha objetivo", nextAction: "Próximo paso", nextActionPlaceholder: "Ej.: conectar el formulario y comprobar un envío real", definitionDone: "Qué significa terminado", definitionDonePlaceholder: "Ej.: publicado, probado en móvil y con README actualizado", putInFocus: "Poner en foco", focusExplanation: "Máximo tres proyectos activos para proteger tu atención.", focusLimit: "Ya tienes tres proyectos en foco. Saca uno antes de añadir este.", cancel: "Cancelar", savePlan: "Guardar plan", projectPlanSaved: "Plan de cierre guardado: {name}", planProject: "Crear plan", editPlan: "Editar plan", next: "Siguiente", noDeadline: "Sin fecha", deadlineOverdue: "Vencido hace {count} d", deadlineToday: "Vence hoy", deadlineDays: "{count} días",
  phaseBacklog: "Por decidir", phaseBuilding: "Construyendo", phaseTesting: "Validando", phaseShipping: "Publicando", phaseDone: "Terminado", phasePaused: "Pausado", phaseAbandoned: "Abandonado con criterio",
  sessionRitual: "Ritual de salida", closeSession: "Cerrar sesión", letGoProject: "Soltar proyecto", closeSessionIntro: "Deja suficiente contexto para que tu yo futuro pueda empezar en menos de dos minutos.", whatMoved: "Qué avanzó hoy", whatMovedPlaceholder: "Cambios completados, decisiones tomadas y comprobaciones realizadas", currentBlocker: "Qué está bloqueando", currentBlockerPlaceholder: "Déjalo vacío si puedes continuar", landingStrip: "Primera acción de la próxima sesión", landingStripPlaceholder: "Una acción verificable de menos de 45 minutos", letGoIntro: "Abandonar una idea a tiempo también es terminar. Guarda la decisión para no volver a evaluarla desde cero.", whyStop: "Por qué ya no merece continuar", whyStopPlaceholder: "Qué cambió: valor, coste, prioridad o viabilidad", whatLearned: "Qué merece conservarse", whatLearnedPlaceholder: "Aprendizaje, código reutilizable o una decisión útil", saveCheckpoint: "Guardar cierre", confirmLetGo: "Cerrar este proyecto", checkpointSaved: "Cierre de sesión guardado: {name}", projectReleased: "Proyecto cerrado con criterio: {name}", whyStopped: "Motivo", doneMeans: "Terminado", noReasonRecorded: "No se registró el motivo.", lastCheckpoint: "Último cierre", reviewExit: "Revisar salida", session: "Cierre",
  guideIntro: "Un sistema breve para reducir trabajo en curso, retomar sin reconstruir el contexto y convertir código casi listo en entregas reales.", openFinishDesk: "Abrir mesa de cierre", methodLimit: "Limita el trabajo abierto", methodLimitText: "Tres proyectos en foco como máximo. Lo demás puede esperar sin competir por atención.", methodNext: "Deja una pista de aterrizaje", methodNextText: "Cierra cada sesión escribiendo una acción de menos de 45 minutos.", methodDone: "Define la salida", methodDoneText: "Decide qué significa publicado antes de añadir nuevas funciones.", rescuePlaybooks: "Protocolos para proyectos atascados", resumeProject: "Retomar después de semanas", resumeProjectText: "Pide al agente que lea README, git status y cambios recientes; después que proponga un único siguiente paso verificable.", unblockProject: "Salir de un bloqueo", unblockProjectText: "Reduce el problema a una decisión reversible o a una prueba de 30 minutos. Registra lo aprendido aunque descartes la idea.", shipProject: "Cerrar y publicar", shipProjectText: "Congela funciones nuevas, ejecuta las comprobaciones, corrige solo bloqueos y publica la versión mínima que cumple tu línea de meta.", releaseProject: "Abandonar sin volver a empezar", releaseProjectText: "Registra por qué deja de compensar y qué aprendizaje conservas. El proyecto queda cerrado, no pendiente.",
  folderCommandLabel: "Escribe o dicta dónde buscar", folderCommandPlaceholder: "Pega una ruta, por ejemplo C:\\Users\\Jota\\Proyectos", dictateFolder: "Dictar carpeta", searchHere: "Buscar aquí", searchFolderAdded: "Carpeta añadida a la búsqueda.", restoreHidden: "Restaurar {count} tarjetas ocultas", hiddenRestored: "Tarjetas ocultas restauradas.",
  publishedProject: "Publicado", noPublicLink: "Sin enlace público", addLinkHint: "Añádelo para abrir la app al instante", openPublished: "Ver publicado", addPublicLink: "Añadir enlace", editLink: "Editar", publicLinkEyebrow: "Destino público", publicLinkHelp: "Pega la dirección HTTPS donde se puede probar el proyecto. Si aún no está publicado, déjalo vacío.", publicLinkLabel: "Enlace de Vercel, Netlify o dominio propio", publicLinkInvalid: "Escribe un enlace HTTPS válido.", customDomain: "Dominio propio", removeLink: "Quitar enlace", saveLink: "Guardar enlace", publicLinkSaved: "Enlace público guardado: {name}", publicLinkRemoved: "Enlace público quitado: {name}", hideCard: "Ocultar tarjeta", hideCardTitle: "¿Quitar esta tarjeta?", hideCardText: "{name} dejará de aparecer en la biblioteca. Su carpeta y sus archivos no se borrarán.", hideCardConfirm: "Quitar tarjeta", cardHidden: "Tarjeta oculta: {name}",
  cleanupEyebrow: "Inspector de almacenamiento", cleanupTitle: "Limpia restos. Conserva el proyecto.", cleanupIntro: "Analiza una carpeta, separa lo regenerable de lo importante y revisa cada elemento antes de enviarlo a la papelera.", folderToAnalyze: "Carpeta de trabajo", analyzeFolder: "Analizar carpeta", analyzing: "Analizando…", cleanupError: "No se pudo analizar la carpeta.", cleanupStepScan: "Detecta", cleanupStepScanText: "Busca dependencias, cachés, compilaciones, registros y carpetas vacías.", cleanupStepReview: "Distingue", cleanupStepReviewText: "Marca lo seguro, separa lo que requiere revisión y bloquea archivos esenciales.", cleanupStepTrash: "Recupera", cleanupStepTrashText: "Envía lo elegido a la papelera del sistema para que siga siendo recuperable.", recoverableSpace: "Espacio potencial", safeToClean: "Seguro", reviewFirst: "Revisar", protectedItems: "Protegido", doNotDelete: "No borrar", nothingToClean: "La carpeta está en orden.", nothingToCleanText: "No encontramos restos habituales ni carpetas vacías que proponer.", cleanupTruncated: "La carpeta es muy grande; se alcanzó el límite de análisis. Puedes limpiar esta selección y volver a analizar.", selectedItems: "{count} elementos seleccionados", recycleBinNote: "Se enviarán a la papelera", moveToTrash: "Enviar a la papelera",
  codexSubtitle: "Agente de OpenAI", claudeSubtitle: "Agente de Anthropic", opencodeSubtitle: "Agente abierto multimodelo",
};

type TranslationKey = keyof typeof es;
type Dictionary = Partial<Record<TranslationKey, string>>;

const en: Dictionary = {
  navLaunch: "Launch", navProjects: "Projects", navCleanup: "Cleanup", navAccounts: "Accounts", navInventory: "Inventory", navUpdates: "Updates", navHelp: "Guide & settings",
  ready: "Ready", notInstalled: "Not installed", plugins: "plugins", skills: "skills", connectedAccount: "Account connected", connectMissing: "Connect account",
  start: "Start", resume: "Resume session", install: "Install",
  launchEyebrow: "Launch bay", launchTitle1: "Choose the project.", launchTitle2: "Power up the agent.", launchIntro: "Three tools, one gateway, and no shared credentials.",
  activeProject: "Active project", chooseFolder: "Choose a folder", changeFolder: "Change folder", availableAgents: "Available agents",
  privateTitle: "Private sessions by design", privateText: "The launcher neither includes nor copies your keys. Each user signs in directly with the chosen provider.",
  accountsEyebrow: "Local identity", accountsTitle: "Your accounts live outside the launcher.", accountsIntro: "Each provider keeps access in the current system profile. When you share the installer, everyone else starts from scratch.",
  connected: "Connected", disconnected: "Not connected", changeAccount: "Change account", signIn: "Sign in", signOut: "Sign out", manageAccount: "Manage account",
  sharedComputer: "For shared computers", sharedComputerText: "Use a separate system account for each person. This also keeps each CLI's history, settings, and stored credentials separate.",
  inventoryEyebrow: "Diagnostics desk", inventoryTitle: "Everything each agent loads.", installedCount: "{count} installed", availableCount: "{count} available", active: "Active", user: "user",
  noPlugins: "No installed plugins were detected.", noSkills: "No skills were detected.", mcpDetected: "Detected MCP servers", technicalOutput: "View technical output", noMcp: "No MCP servers detected or tool not installed.", openDocs: "Open {tool} documentation",
  maintenance: "Maintenance", updatesTitle: "Clear versions, controlled changes.", updatesIntro: "Checks are automatic. Updates open the terminal so you can see exactly what changes.", checking: "Checking…", checkNow: "Check now", noHiddenInstallers: "No hidden installers are run.",
  notChecked: "Not checked", detectedInstall: "Installation detected", notYetInstalled: "Not installed yet", current: "Current", available: "Available", upToDate: "Up to date", update: "Update", launcherChannel: "Launcher update channel", searchUpdate: "Check for updates",
  guideEyebrow: "Guide & settings", guideTitle: "Fewer open projects. More shipped projects.", howToStart: "Getting started", stepProject: "Choose a project", stepProjectText: "Select the folder that contains your code.", stepAccount: "Connect your account", stepAccountText: "The provider opens its own secure sign-in.", stepAgent: "Start the agent", stepAgentText: "The terminal opens in the correct folder.",
  preferences: "Preferences", checkTools: "Check tools", checkToolsText: "Look for new versions at startup", updateLauncher: "Update the launcher", updateLauncherText: "Check the release channel", startSystem: "Start with the system", startSystemText: "Open the panel when you sign in",
  missingTool: "Missing a tool?", officialRequirements: "View its official installation guide and requirements.", localPanel: "Local panel", readingSystem: "Reading the system…", shellReady: "{shell} ready", refreshStatus: "Refresh status", language: "Language", settingsSaved: "Preferences saved.", diagnosticError: "The diagnostic could not be completed.",
  projectsEyebrow: "Local library", projectsTitle: "Find one. Finish it.", projectsIntro: "Search even when you do not remember the exact name, regain context, and keep the next step visible until it ships.", addProjectFolder: "Add folder", scanProjects: "Find projects", scanningProjects: "Searching…", useProject: "Use project", openFolder: "Open folder", projectSelected: "Project selected: {name}", projectFolderOpened: "Folder opened.", noProjectsTitle: "No projects found yet.", noProjectsText: "Add your workspace. Local apps and plugins are included even when they are not on GitHub.", noProjectDescription: "No description yet. Add a README to remember what it does.", localFolder: "Local folder", detectedProjects: "{count} projects detected", searchLocations: "Search folders", automaticLocations: "Common locations included", removeRoot: "Remove", folderOpenError: "The folder could not be opened.",
  projectSearchPlaceholder: "Search by name, description, technology, or path…", searchProjectsLabel: "Search projects", clearSearch: "Clear search", projectFilters: "Project filters", filterAll: "All", filterFocus: "In focus", filterRisk: "At risk", filterUnplanned: "Unplanned", filterClosed: "Closed", resultsCount: "{count} matches", noSearchTitle: "No project matches.", noSearchText: "Try part of its name, a technology, or a word from its description.",
  focusDesk: "Finish desk", focusDeskEmpty: "Choose what deserves to be finished.", focusDeskEmptyText: "Put up to three projects in focus. The launcher will keep the next move visible.", planFirstProject: "Plan the first", finishNow: "Push this now", continueProject: "Continue", missingNextAction: "A small, concrete next action is missing.", blockedBy: "Blocked by",
  finishPlan: "Finish plan", finishPlanIntro: "Do not plan the whole project. Define the finish line and the next step you can complete in one session.", phase: "Phase", deadline: "Target date", nextAction: "Next action", nextActionPlaceholder: "E.g. connect the form and verify one real submission", definitionDone: "What done means", definitionDonePlaceholder: "E.g. deployed, mobile-tested, and README updated", putInFocus: "Put in focus", focusExplanation: "Maximum three active projects to protect your attention.", focusLimit: "Three projects are already in focus. Remove one before adding this.", cancel: "Cancel", savePlan: "Save plan", projectPlanSaved: "Finish plan saved: {name}", planProject: "Create plan", editPlan: "Edit plan", next: "Next", noDeadline: "No date", deadlineOverdue: "Overdue by {count}d", deadlineToday: "Due today", deadlineDays: "{count} days",
  phaseBacklog: "To decide", phaseBuilding: "Building", phaseTesting: "Validating", phaseShipping: "Shipping", phaseDone: "Done", phasePaused: "Paused", phaseAbandoned: "Consciously abandoned",
  sessionRitual: "Exit ritual", closeSession: "Close session", letGoProject: "Let project go", closeSessionIntro: "Leave enough context for your future self to start in under two minutes.", whatMoved: "What moved today", whatMovedPlaceholder: "Completed changes, decisions, and checks", currentBlocker: "What is blocking you", currentBlockerPlaceholder: "Leave blank if work can continue", landingStrip: "First action next session", landingStripPlaceholder: "One verifiable action under 45 minutes", letGoIntro: "Stopping an idea in time is also finishing. Save the decision so you never evaluate it from scratch again.", whyStop: "Why it no longer deserves work", whyStopPlaceholder: "What changed: value, cost, priority, or feasibility", whatLearned: "What is worth keeping", whatLearnedPlaceholder: "A lesson, reusable code, or a useful decision", saveCheckpoint: "Save checkpoint", confirmLetGo: "Close this project", checkpointSaved: "Session checkpoint saved: {name}", projectReleased: "Project consciously closed: {name}", whyStopped: "Reason", doneMeans: "Done", noReasonRecorded: "No reason was recorded.", lastCheckpoint: "Last checkpoint", reviewExit: "Review exit", session: "Checkpoint",
  guideIntro: "A compact system to reduce work in progress, regain context quickly, and turn nearly-finished code into real releases.", openFinishDesk: "Open finish desk", methodLimit: "Limit open work", methodLimitText: "Keep at most three projects in focus. Everything else can wait without competing for attention.", methodNext: "Leave a landing strip", methodNextText: "End every session by writing an action that takes less than 45 minutes.", methodDone: "Define the exit", methodDoneText: "Decide what shipped means before adding more features.", rescuePlaybooks: "Playbooks for stuck projects", resumeProject: "Resume after weeks", resumeProjectText: "Ask the agent to read the README, git status, and recent changes, then propose one verifiable next step.", unblockProject: "Get unstuck", unblockProjectText: "Reduce the problem to a reversible decision or a 30-minute experiment. Record what you learned even if you discard the idea.", shipProject: "Close and ship", shipProjectText: "Freeze new features, run checks, fix blockers only, and release the smallest version that meets your finish line.", releaseProject: "Stop without restarting later", releaseProjectText: "Record why it is no longer worth it and what you learned. The project becomes closed, not pending.",
  folderCommandLabel: "Type or dictate where to search", folderCommandPlaceholder: "Paste a path, for example C:\\Users\\You\\Projects", dictateFolder: "Dictate folder", searchHere: "Search here", searchFolderAdded: "Folder added to the search.", restoreHidden: "Restore {count} hidden cards", hiddenRestored: "Hidden cards restored.",
  publishedProject: "Published", noPublicLink: "No public link", addLinkHint: "Add it to open the app instantly", openPublished: "View live", addPublicLink: "Add link", editLink: "Edit", publicLinkEyebrow: "Public destination", publicLinkHelp: "Paste the HTTPS address where the project can be tried. Leave it empty if it is not deployed yet.", publicLinkLabel: "Vercel, Netlify, or custom-domain link", publicLinkInvalid: "Enter a valid HTTPS link.", customDomain: "Custom domain", removeLink: "Remove link", saveLink: "Save link", publicLinkSaved: "Public link saved: {name}", publicLinkRemoved: "Public link removed: {name}", hideCard: "Hide card", hideCardTitle: "Remove this card?", hideCardText: "{name} will disappear from the library. Its folder and files will not be deleted.", hideCardConfirm: "Remove card", cardHidden: "Card hidden: {name}",
  cleanupEyebrow: "Storage inspector", cleanupTitle: "Clear leftovers. Keep the project.", cleanupIntro: "Analyze a folder, separate rebuildable output from important work, and review every item before moving it to the recycle bin.", folderToAnalyze: "Working folder", analyzeFolder: "Analyze folder", analyzing: "Analyzing…", cleanupError: "The folder could not be analyzed.", cleanupStepScan: "Detect", cleanupStepScanText: "Find dependencies, caches, builds, logs, and empty folders.", cleanupStepReview: "Distinguish", cleanupStepReviewText: "Mark safe items, separate those needing review, and lock essential files.", cleanupStepTrash: "Recover", cleanupStepTrashText: "Move selected items to the system recycle bin so they remain recoverable.", recoverableSpace: "Potential space", safeToClean: "Safe", reviewFirst: "Review", protectedItems: "Protected", doNotDelete: "Do not delete", nothingToClean: "This folder is in order.", nothingToCleanText: "No common leftovers or empty folders were found.", cleanupTruncated: "This folder is very large and reached the scan limit. Clean this selection and scan again.", selectedItems: "{count} items selected", recycleBinNote: "They will go to the recycle bin", moveToTrash: "Move to recycle bin",
  codexSubtitle: "OpenAI agent", claudeSubtitle: "Anthropic agent", opencodeSubtitle: "Open multimodel agent",
};

const fr: Dictionary = {
  navLaunch: "Lancer", navProjects: "Projets", navAccounts: "Comptes", navInventory: "Inventaire", navUpdates: "Mises à jour", navHelp: "Guide et réglages",
  ready: "Prêt", notInstalled: "Non installé", plugins: "plugins", skills: "skills", connectedAccount: "Compte connecté", connectMissing: "Connexion requise",
  start: "Démarrer", resume: "Reprendre la session", install: "Installer",
  launchEyebrow: "Baie de lancement", launchTitle1: "Choisissez le projet.", launchTitle2: "Activez l’agent.", launchIntro: "Trois outils, une seule porte d’entrée et aucun identifiant partagé.",
  activeProject: "Projet actif", chooseFolder: "Choisir un dossier", changeFolder: "Changer de dossier", availableAgents: "Agents disponibles",
  privateTitle: "Sessions privées par conception", privateText: "Le launcher n’inclut ni ne copie vos clés. Chaque utilisateur se connecte directement auprès du fournisseur choisi.",
  accountsEyebrow: "Identité locale", accountsTitle: "Vos comptes restent hors du launcher.", accountsIntro: "Chaque fournisseur conserve l’accès dans le profil système actuel. Lorsque vous partagez l’installateur, les autres repartent de zéro.",
  connected: "Connecté", disconnected: "Non connecté", changeAccount: "Changer de compte", signIn: "Se connecter", signOut: "Se déconnecter", manageAccount: "Gérer le compte",
  sharedComputer: "Pour les ordinateurs partagés", sharedComputerText: "Utilisez un compte système différent pour chaque personne. Les historiques, réglages et identifiants enregistrés par chaque CLI restent ainsi séparés.",
  inventoryEyebrow: "Table de diagnostic", inventoryTitle: "Tout ce que chaque agent charge.", installedCount: "{count} installés", availableCount: "{count} disponibles", active: "Actif", user: "utilisateur",
  noPlugins: "Aucun plugin installé détecté.", noSkills: "Aucun skill détecté.", mcpDetected: "Serveurs MCP détectés", technicalOutput: "Voir la sortie technique", noMcp: "Aucun serveur MCP détecté ou outil non installé.", openDocs: "Ouvrir la documentation de {tool}",
  maintenance: "Maintenance", updatesTitle: "Versions claires, changements maîtrisés.", updatesIntro: "La vérification est automatique. Les mises à jour ouvrent le terminal afin que vous puissiez voir précisément les changements.", checking: "Vérification…", checkNow: "Vérifier maintenant", noHiddenInstallers: "Aucun installateur caché n’est exécuté.",
  notChecked: "Non vérifié", detectedInstall: "Installation détectée", notYetInstalled: "Pas encore installé", current: "Actuelle", available: "Disponible", upToDate: "À jour", update: "Mettre à jour", launcherChannel: "Canal de mise à jour du launcher", searchUpdate: "Rechercher une mise à jour",
  guideEyebrow: "Guide et réglages", guideTitle: "Une porte, trois façons de travailler.", howToStart: "Bien démarrer", stepProject: "Choisissez un projet", stepProjectText: "Sélectionnez le dossier contenant votre code.", stepAccount: "Connectez votre compte", stepAccountText: "Le fournisseur ouvre sa propre connexion sécurisée.", stepAgent: "Démarrez l’agent", stepAgentText: "Le terminal s’ouvre dans le bon dossier.",
  preferences: "Préférences", checkTools: "Vérifier les outils", checkToolsText: "Rechercher de nouvelles versions au démarrage", updateLauncher: "Mettre à jour le launcher", updateLauncherText: "Vérifier le canal des versions", startSystem: "Démarrer avec le système", startSystemText: "Ouvrir le panneau à la connexion",
  missingTool: "Un outil vous manque ?", officialRequirements: "Consultez son installation et ses prérequis officiels.", localPanel: "Panneau local", readingSystem: "Lecture du système…", shellReady: "{shell} prêt", refreshStatus: "Actualiser l’état", language: "Langue", settingsSaved: "Préférences enregistrées.", diagnosticError: "Le diagnostic n’a pas pu être terminé.",
  projectsEyebrow: "Bibliothèque locale", projectsTitle: "Vos projets, prêts à s’ouvrir.", projectsIntro: "Nous réunissons vos projets et dossiers créés avec l’IA, lisons leur README et affichons la stack, le dépôt et le déploiement.", addProjectFolder: "Ajouter un dossier", scanProjects: "Rechercher des projets", scanningProjects: "Recherche…", useProject: "Utiliser le projet", openFolder: "Ouvrir le dossier", projectSelected: "Projet sélectionné : {name}", projectFolderOpened: "Dossier ouvert.", noProjectsTitle: "Aucun projet trouvé pour le moment.", noProjectsText: "Ajoutez votre espace de travail. Les apps et plugins locaux sont inclus même sans GitHub.", noProjectDescription: "Pas encore de description. Ajoutez un README pour vous souvenir de son rôle.", localFolder: "Dossier local", detectedProjects: "{count} projets détectés", searchLocations: "Dossiers de recherche", automaticLocations: "Emplacements habituels inclus", removeRoot: "Retirer", folderOpenError: "Impossible d’ouvrir le dossier.",
  codexSubtitle: "Agent d’OpenAI", claudeSubtitle: "Agent d’Anthropic", opencodeSubtitle: "Agent ouvert multimodèle",
};

const pt: Dictionary = {
  navLaunch: "Iniciar", navProjects: "Projetos", navAccounts: "Contas", navInventory: "Inventário", navUpdates: "Atualizações", navHelp: "Guia e definições",
  ready: "Pronto", notInstalled: "Não instalado", plugins: "plugins", skills: "skills", connectedAccount: "Conta ligada", connectMissing: "Falta ligar",
  start: "Iniciar", resume: "Continuar sessão", install: "Instalar",
  launchEyebrow: "Baía de lançamento", launchTitle1: "Escolha o projeto.", launchTitle2: "Ative o agente.", launchIntro: "Três ferramentas, uma única entrada e nenhuma credencial partilhada.",
  activeProject: "Projeto ativo", chooseFolder: "Escolher uma pasta", changeFolder: "Mudar pasta", availableAgents: "Agentes disponíveis",
  privateTitle: "Sessões privadas por design", privateText: "O launcher não inclui nem copia as suas chaves. Cada utilizador inicia sessão diretamente no fornecedor escolhido.",
  accountsEyebrow: "Identidade local", accountsTitle: "As suas contas vivem fora do launcher.", accountsIntro: "Cada fornecedor mantém o acesso no perfil atual do sistema. Ao partilhar o instalador, os outros começam do zero.",
  connected: "Ligada", disconnected: "Não ligada", changeAccount: "Mudar conta", signIn: "Iniciar sessão", signOut: "Terminar sessão", manageAccount: "Gerir conta",
  sharedComputer: "Para computadores partilhados", sharedComputerText: "Use uma conta do sistema diferente para cada pessoa. Assim, os históricos, as definições e as credenciais guardadas por cada CLI também ficam separados.",
  inventoryEyebrow: "Mesa de diagnóstico", inventoryTitle: "Tudo o que cada agente carrega.", installedCount: "{count} instalados", availableCount: "{count} disponíveis", active: "Ativo", user: "utilizador",
  noPlugins: "Não foram detetados plugins instalados.", noSkills: "Não foram detetados skills.", mcpDetected: "Servidores MCP detetados", technicalOutput: "Ver saída técnica", noMcp: "Nenhum servidor MCP detetado ou ferramenta não instalada.", openDocs: "Abrir documentação de {tool}",
  maintenance: "Manutenção", updatesTitle: "Versões claras, alterações controladas.", updatesIntro: "A verificação é automática. As atualizações abrem o terminal para que possa ver exatamente o que muda.", checking: "A verificar…", checkNow: "Verificar agora", noHiddenInstallers: "Não são executados instaladores ocultos.",
  notChecked: "Não verificado", detectedInstall: "Instalação detetada", notYetInstalled: "Ainda não está instalado", current: "Atual", available: "Disponível", upToDate: "Atualizado", update: "Atualizar", launcherChannel: "Canal de atualização do launcher", searchUpdate: "Procurar atualização",
  guideEyebrow: "Guia e definições", guideTitle: "Uma entrada, três formas de trabalhar.", howToStart: "Como começar", stepProject: "Escolha um projeto", stepProjectText: "Selecione a pasta que contém o seu código.", stepAccount: "Ligue a sua conta", stepAccountText: "O fornecedor abre o seu próprio acesso seguro.", stepAgent: "Inicie o agente", stepAgentText: "O terminal abre na pasta correta.",
  preferences: "Preferências", checkTools: "Verificar ferramentas", checkToolsText: "Procurar novas versões ao iniciar", updateLauncher: "Atualizar o launcher", updateLauncherText: "Verificar o canal de versões", startSystem: "Iniciar com o sistema", startSystemText: "Abrir o painel ao entrar na conta",
  missingTool: "Falta alguma ferramenta?", officialRequirements: "Consulte a instalação e os requisitos oficiais.", localPanel: "Painel local", readingSystem: "A ler o sistema…", shellReady: "{shell} pronto", refreshStatus: "Atualizar estado", language: "Idioma", settingsSaved: "Preferências guardadas.", diagnosticError: "Não foi possível concluir o diagnóstico.",
  projectsEyebrow: "Biblioteca local", projectsTitle: "Os seus projetos, prontos a abrir.", projectsIntro: "Reunimos projetos e pastas criados com IA, lemos o README e mostramos stack, repositório e publicação para recordar onde ficou.", addProjectFolder: "Adicionar pasta", scanProjects: "Procurar projetos", scanningProjects: "A procurar…", useProject: "Usar projeto", openFolder: "Abrir pasta", projectSelected: "Projeto selecionado: {name}", projectFolderOpened: "Pasta aberta.", noProjectsTitle: "Ainda não encontrámos projetos.", noProjectsText: "Adicione a sua pasta de trabalho. Apps e plugins locais também entram, mesmo sem GitHub.", noProjectDescription: "Ainda sem descrição. Adicione um README para recordar o que faz.", localFolder: "Pasta local", detectedProjects: "{count} projetos detetados", searchLocations: "Pastas de pesquisa", automaticLocations: "Localizações habituais incluídas", removeRoot: "Remover", folderOpenError: "Não foi possível abrir a pasta.",
  codexSubtitle: "Agente da OpenAI", claudeSubtitle: "Agente da Anthropic", opencodeSubtitle: "Agente aberto multimodelo",
};

const it: Dictionary = {
  navLaunch: "Avvia", navProjects: "Progetti", navAccounts: "Account", navInventory: "Inventario", navUpdates: "Aggiornamenti", navHelp: "Guida e impostazioni",
  ready: "Pronto", notInstalled: "Non installato", plugins: "plugin", skills: "skill", connectedAccount: "Account collegato", connectMissing: "Da collegare",
  start: "Avvia", resume: "Continua sessione", install: "Installa",
  launchEyebrow: "Baia di lancio", launchTitle1: "Scegli il progetto.", launchTitle2: "Attiva l’agente.", launchIntro: "Tre strumenti, un solo punto di accesso e nessuna credenziale condivisa.",
  activeProject: "Progetto attivo", chooseFolder: "Scegli una cartella", changeFolder: "Cambia cartella", availableAgents: "Agenti disponibili",
  privateTitle: "Sessioni private per progettazione", privateText: "Il launcher non include né copia le tue chiavi. Ogni utente accede direttamente tramite il provider scelto.",
  accountsEyebrow: "Identità locale", accountsTitle: "I tuoi account restano fuori dal launcher.", accountsIntro: "Ogni provider conserva l’accesso nel profilo di sistema corrente. Quando condividi l’installer, gli altri iniziano da zero.",
  connected: "Collegato", disconnected: "Non collegato", changeAccount: "Cambia account", signIn: "Accedi", signOut: "Esci", manageAccount: "Gestisci account",
  sharedComputer: "Per computer condivisi", sharedComputerText: "Usa un account di sistema diverso per ogni persona. In questo modo anche cronologia, impostazioni e credenziali salvate da ogni CLI restano separate.",
  inventoryEyebrow: "Banco di diagnostica", inventoryTitle: "Tutto ciò che ogni agente carica.", installedCount: "{count} installati", availableCount: "{count} disponibili", active: "Attivo", user: "utente",
  noPlugins: "Nessun plugin installato rilevato.", noSkills: "Nessuna skill rilevata.", mcpDetected: "Server MCP rilevati", technicalOutput: "Vedi output tecnico", noMcp: "Nessun server MCP rilevato o strumento non installato.", openDocs: "Apri la documentazione di {tool}",
  maintenance: "Manutenzione", updatesTitle: "Versioni chiare, modifiche sotto controllo.", updatesIntro: "Il controllo è automatico. Gli aggiornamenti aprono il terminale così puoi vedere esattamente cosa cambia.", checking: "Controllo…", checkNow: "Controlla ora", noHiddenInstallers: "Non vengono eseguiti installer nascosti.",
  notChecked: "Non controllato", detectedInstall: "Installazione rilevata", notYetInstalled: "Non ancora installato", current: "Attuale", available: "Disponibile", upToDate: "Aggiornato", update: "Aggiorna", launcherChannel: "Canale di aggiornamento del launcher", searchUpdate: "Cerca aggiornamenti",
  guideEyebrow: "Guida e impostazioni", guideTitle: "Un accesso, tre modi di lavorare.", howToStart: "Come iniziare", stepProject: "Scegli un progetto", stepProjectText: "Seleziona la cartella che contiene il codice.", stepAccount: "Collega il tuo account", stepAccountText: "Il provider apre il proprio accesso sicuro.", stepAgent: "Avvia l’agente", stepAgentText: "Il terminale si apre nella cartella corretta.",
  preferences: "Preferenze", checkTools: "Controlla strumenti", checkToolsText: "Cerca nuove versioni all’avvio", updateLauncher: "Aggiorna il launcher", updateLauncherText: "Controlla il canale delle versioni", startSystem: "Avvia con il sistema", startSystemText: "Apri il pannello all’accesso",
  missingTool: "Manca uno strumento?", officialRequirements: "Consulta l’installazione e i requisiti ufficiali.", localPanel: "Pannello locale", readingSystem: "Lettura del sistema…", shellReady: "{shell} pronto", refreshStatus: "Aggiorna stato", language: "Lingua", settingsSaved: "Preferenze salvate.", diagnosticError: "Impossibile completare la diagnostica.",
  projectsEyebrow: "Libreria locale", projectsTitle: "I tuoi progetti, pronti da aprire.", projectsIntro: "Riuniamo progetti e cartelle creati con l’IA, leggiamo il README e mostriamo stack, repository e distribuzione per ricordare dove eri rimasto.", addProjectFolder: "Aggiungi cartella", scanProjects: "Cerca progetti", scanningProjects: "Ricerca…", useProject: "Usa progetto", openFolder: "Apri cartella", projectSelected: "Progetto selezionato: {name}", projectFolderOpened: "Cartella aperta.", noProjectsTitle: "Nessun progetto trovato.", noProjectsText: "Aggiungi la cartella di lavoro. Anche app e plugin locali vengono inclusi senza GitHub.", noProjectDescription: "Nessuna descrizione. Aggiungi un README per ricordare cosa fa.", localFolder: "Cartella locale", detectedProjects: "{count} progetti rilevati", searchLocations: "Cartelle di ricerca", automaticLocations: "Posizioni abituali incluse", removeRoot: "Rimuovi", folderOpenError: "Impossibile aprire la cartella.",
  codexSubtitle: "Agente OpenAI", claudeSubtitle: "Agente Anthropic", opencodeSubtitle: "Agente aperto multimodello",
};

const de: Dictionary = {
  navLaunch: "Starten", navProjects: "Projekte", navAccounts: "Konten", navInventory: "Inventar", navUpdates: "Aktualisierungen", navHelp: "Hilfe & Einstellungen",
  ready: "Bereit", notInstalled: "Nicht installiert", plugins: "Plugins", skills: "Skills", connectedAccount: "Konto verbunden", connectMissing: "Verbindung fehlt",
  start: "Starten", resume: "Sitzung fortsetzen", install: "Installieren",
  launchEyebrow: "Startbereich", launchTitle1: "Projekt auswählen.", launchTitle2: "Agenten starten.", launchIntro: "Drei Werkzeuge, ein Zugang und keine gemeinsam genutzten Anmeldedaten.",
  activeProject: "Aktives Projekt", chooseFolder: "Ordner auswählen", changeFolder: "Ordner wechseln", availableAgents: "Verfügbare Agenten",
  privateTitle: "Private Sitzungen als Grundprinzip", privateText: "Der Launcher enthält oder kopiert keine Schlüssel. Jeder Benutzer meldet sich direkt beim gewählten Anbieter an.",
  accountsEyebrow: "Lokale Identität", accountsTitle: "Deine Konten bleiben außerhalb des Launchers.", accountsIntro: "Jeder Anbieter speichert den Zugang im aktuellen Systemprofil. Wird der Installer geteilt, beginnen andere bei null.",
  connected: "Verbunden", disconnected: "Nicht verbunden", changeAccount: "Konto wechseln", signIn: "Anmelden", signOut: "Abmelden", manageAccount: "Konto verwalten",
  sharedComputer: "Für gemeinsam genutzte Computer", sharedComputerText: "Verwende für jede Person ein eigenes Systemkonto. So bleiben auch Verläufe, Einstellungen und gespeicherte Zugangsdaten der einzelnen CLIs getrennt.",
  inventoryEyebrow: "Diagnosebereich", inventoryTitle: "Alles, was jeder Agent lädt.", installedCount: "{count} installiert", availableCount: "{count} verfügbar", active: "Aktiv", user: "Benutzer",
  noPlugins: "Keine installierten Plugins erkannt.", noSkills: "Keine Skills erkannt.", mcpDetected: "Erkannte MCP-Server", technicalOutput: "Technische Ausgabe anzeigen", noMcp: "Keine MCP-Server erkannt oder Werkzeug nicht installiert.", openDocs: "Dokumentation für {tool} öffnen",
  maintenance: "Wartung", updatesTitle: "Klare Versionen, kontrollierte Änderungen.", updatesIntro: "Die Prüfung läuft automatisch. Aktualisierungen öffnen das Terminal, damit du genau siehst, was sich ändert.", checking: "Wird geprüft…", checkNow: "Jetzt prüfen", noHiddenInstallers: "Es werden keine versteckten Installer ausgeführt.",
  notChecked: "Nicht geprüft", detectedInstall: "Installation erkannt", notYetInstalled: "Noch nicht installiert", current: "Aktuell", available: "Verfügbar", upToDate: "Aktuell", update: "Aktualisieren", launcherChannel: "Aktualisierungskanal des Launchers", searchUpdate: "Nach Aktualisierung suchen",
  guideEyebrow: "Hilfe & Einstellungen", guideTitle: "Ein Zugang, drei Arbeitsweisen.", howToStart: "Erste Schritte", stepProject: "Projekt auswählen", stepProjectText: "Wähle den Ordner aus, der deinen Code enthält.", stepAccount: "Konto verbinden", stepAccountText: "Der Anbieter öffnet seine eigene sichere Anmeldung.", stepAgent: "Agenten starten", stepAgentText: "Das Terminal öffnet sich im richtigen Ordner.",
  preferences: "Einstellungen", checkTools: "Werkzeuge prüfen", checkToolsText: "Beim Start nach neuen Versionen suchen", updateLauncher: "Launcher aktualisieren", updateLauncherText: "Versionskanal prüfen", startSystem: "Mit dem System starten", startSystemText: "Panel bei der Anmeldung öffnen",
  missingTool: "Fehlt ein Werkzeug?", officialRequirements: "Offizielle Installation und Anforderungen ansehen.", localPanel: "Lokales Panel", readingSystem: "System wird gelesen…", shellReady: "{shell} bereit", refreshStatus: "Status aktualisieren", language: "Sprache", settingsSaved: "Einstellungen gespeichert.", diagnosticError: "Die Diagnose konnte nicht abgeschlossen werden.",
  projectsEyebrow: "Lokale Bibliothek", projectsTitle: "Deine Projekte, sofort startklar.", projectsIntro: "Wir sammeln deine mit KI erstellten Projekte und Ordner, lesen die README und zeigen Stack, Repository und Deployment.", addProjectFolder: "Ordner hinzufügen", scanProjects: "Projekte suchen", scanningProjects: "Suche…", useProject: "Projekt verwenden", openFolder: "Ordner öffnen", projectSelected: "Projekt ausgewählt: {name}", projectFolderOpened: "Ordner geöffnet.", noProjectsTitle: "Noch keine Projekte gefunden.", noProjectsText: "Füge deinen Arbeitsordner hinzu. Lokale Apps und Plugins werden auch ohne GitHub erkannt.", noProjectDescription: "Noch keine Beschreibung. Ergänze eine README als Gedächtnisstütze.", localFolder: "Lokaler Ordner", detectedProjects: "{count} Projekte erkannt", searchLocations: "Suchordner", automaticLocations: "Übliche Speicherorte enthalten", removeRoot: "Entfernen", folderOpenError: "Der Ordner konnte nicht geöffnet werden.",
  codexSubtitle: "Agent von OpenAI", claudeSubtitle: "Agent von Anthropic", opencodeSubtitle: "Offener Multimodell-Agent",
};

const dictionaries: Record<Language, Dictionary> = { es, en, fr, pt, it, de };

export function translate(language: Language, key: TranslationKey, values: Record<string, string | number> = {}): string {
  return Object.entries(values).reduce(
    (text, [name, value]) => text.replaceAll(`{${name}}`, String(value)),
    dictionaries[language][key] || en[key] || es[key],
  );
}

export type Translator = (key: TranslationKey, values?: Record<string, string | number>) => string;
